name: Coffee Shop CI
on:
  push:
    branches: [main]
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm i

      - name: Run unit tests
        run: |
          npm run test:coverage --setupFiles ../../src/tests/vitest-setup.js

      - name: Generate unit test coverage report
        uses: actions/upload-artifact@v3
        with:
          name: Relatório de testes
          path: coverage/

  static-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm i

      - name: Run linting tests
        run: npm run lint --fix

  cypress-tests:
    runs-on: ubuntu-latest
    needs: [unit-tests, static-tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm i

      - name: Cypress tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          build: npm run build
          start: npm start

      - name: Generate Cypress video artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Vídeos dos testes cypress
          path: cypress/videos

  build:
    runs-on: ubuntu-latest 
    needs: cypress-tests 
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm i

      - name: Build application
        run: npm run build

      - name: Save project build in artifact
        uses: actions/upload-artifact@v3
        with:
          name: Aplicação empacotada 
          path: .next/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy project Artifacts to vercel
        run: vercel deploy --prebuild --prod --token=${{ secrets.VERCEL_TOKEN }}

  notification:
    runs-on: ubuntu-latest
    needs: deploy
    steps: 
      - name: Sending success message email
        uses: actions/checkout@v3
      - run:  sh .github/scripts/send_email.sh
        env:
          EMAIL: avnerj.g.r@gmail.com